// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import "dart:core";
import 'package:demo/src/Animal.dart' as prefix1;
import 'package:proxiable/src/annotation/proxiable.dart' as prefix0;

// ignore_for_file: unnecessary_const

// ignore:unused_import
import "package:reflectable/mirrors.dart" as m;
// ignore:unused_import
import "package:reflectable/src/reflectable_builder_based.dart" as r;
// ignore:unused_import
import "package:reflectable/reflectable.dart" as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Proxiable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r"Animal",
            r".Animal",
            7,
            0,
            const prefix0.Proxiable(),
            const <int>[0, 1],
            const <int>[2, 3, 4, 5, 6, 0],
            const <int>[],
            -1,
            {},
            {},
            {r"": (b) => () => b ? prefix1.Animal() : null},
            -1,
            -1,
            const <int>[-1],
            null,
            null)
      ],
      <m.DeclarationMirror>[
        r.MethodMirrorImpl(r"walk", 262146, 0, null, -1, -1, null,
            const <int>[], const prefix0.Proxiable(), null),
        r.MethodMirrorImpl(r"", 64, 0, -1, -1, -1, null, const <int>[],
            const prefix0.Proxiable(), null),
        r.MethodMirrorImpl(r"==", 131074, null, -1, -1, -1, null,
            const <int>[0], const prefix0.Proxiable(), null),
        r.MethodMirrorImpl(r"toString", 131074, null, -1, -1, -1, null,
            const <int>[], const prefix0.Proxiable(), null),
        r.MethodMirrorImpl(r"noSuchMethod", 65538, null, null, -1, -1, null,
            const <int>[1], const prefix0.Proxiable(), null),
        r.MethodMirrorImpl(r"hashCode", 131075, null, -1, -1, -1, null,
            const <int>[], const prefix0.Proxiable(), null),
        r.MethodMirrorImpl(r"runtimeType", 131075, null, -1, -1, -1, null,
            const <int>[], const prefix0.Proxiable(), null)
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r"other", 16390, 2, const prefix0.Proxiable(),
            null, -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(r"invocation", 32774, 4,
            const prefix0.Proxiable(), -1, -1, -1, null, null, null, null)
      ],
      <Type>[prefix1.Animal],
      1,
      {
        r"==": (dynamic instance) => (x) => instance == x,
        r"toString": (dynamic instance) => instance.toString,
        r"noSuchMethod": (dynamic instance) => instance.noSuchMethod,
        r"hashCode": (dynamic instance) => instance.hashCode,
        r"runtimeType": (dynamic instance) => instance.runtimeType,
        r"walk": (dynamic instance) => instance.walk
      },
      {},
      null,
      [])
};

final _memberSymbolMap = null;

initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
